"""Freqtrade cross-validation adapter.

Re-executes the native engine's trade decisions inside freqtrade's
backtesting engine via a generated SignalReplay strategy:

- OHLCV for the window is written as a feather file into a throwaway
  freqtrade userdir.
- Native trade entry/exit timestamps become enter/exit signal columns in a
  CSV the generated strategy merges in populate_indicators.
- Freqtrade re-prices every fill itself (next-candle open after signal,
  configured fee) — native fill prices are not trusted.

Requires the `freqtrade` CLI on PATH.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
import zipfile
from pathlib import Path

import pandas as pd

from .native_engine import FrameworkRun

_STRATEGY_TEMPLATE = '''"""Auto-generated by quant-loop/validation: replay native signals in freqtrade."""
import os

import pandas as pd
from freqtrade.strategy import IStrategy


class SignalReplay(IStrategy):
    INTERFACE_VERSION = 3
    timeframe = "%(timeframe)s"
    can_short = True
    process_only_new_candles = True
    startup_candle_count = 0
    minimal_roi = {"0": 100}   # never triggers; exits come from signals
    stoploss = -1.0            # disabled; exits come from signals

    def populate_indicators(self, dataframe, metadata):
        signals = pd.read_csv(os.environ["REPLAY_SIGNALS_CSV"], parse_dates=["date"])
        signals["date"] = pd.to_datetime(signals["date"], utc=True)
        dataframe = dataframe.merge(signals, on="date", how="left")
        for col in ("enter_long_sig", "exit_long_sig", "enter_short_sig", "exit_short_sig"):
            dataframe[col] = dataframe[col].fillna(0).astype(int)
        return dataframe

    def populate_entry_trend(self, dataframe, metadata):
        dataframe.loc[dataframe["enter_long_sig"] == 1, "enter_long"] = 1
        dataframe.loc[dataframe["enter_short_sig"] == 1, "enter_short"] = 1
        return dataframe

    def populate_exit_trend(self, dataframe, metadata):
        dataframe.loc[dataframe["exit_long_sig"] == 1, "exit_long"] = 1
        dataframe.loc[dataframe["exit_short_sig"] == 1, "exit_short"] = 1
        return dataframe
'''

_TIMEFRAME_MAP = {"1m": "1m", "5m": "5m", "15m": "15m", "1h": "1h", "4h": "4h", "1d": "1d"}


class FreqtradeReplayError(RuntimeError):
    pass


def _pair(symbol: str) -> str:
    base = symbol.upper().replace("USDT", "")
    return f"{base}/USDT:USDT"


def _pair_file_stem(symbol: str) -> str:
    base = symbol.upper().replace("USDT", "")
    return f"{base}_USDT_USDT"


def _write_feather(df: pd.DataFrame, path: Path, timeframe: str) -> None:
    out = df.copy()
    # freqtrade compares the date column against tz-aware TimeRange bounds, so
    # keep dates tz-aware UTC (its own download pipeline stores tz-aware too)
    if out.index.tz is None:
        out.index = out.index.tz_localize("UTC")
    else:
        out.index = out.index.tz_convert("UTC")
    out = out.reset_index()
    out.columns = ["date" if c in ("openTime", "index") else c for c in out.columns]
    out = out[["date", "open", "high", "low", "close", "volume"]]
    path.parent.mkdir(parents=True, exist_ok=True)
    out.to_feather(path)


def _write_signals(native_trades: list[dict], path: Path) -> None:
    rows = []
    for t in native_trades:
        e = pd.Timestamp(t["entry_date"])
        x = pd.Timestamp(t["exit_date"])
        if e.tzinfo is None:
            e = e.tz_localize("UTC")
        if x.tzinfo is None:
            x = x.tz_localize("UTC")
        is_long = t["direction"] == "long"
        rows.append({"date": e, "enter_long_sig": int(is_long), "exit_long_sig": 0,
                     "enter_short_sig": int(not is_long), "exit_short_sig": 0})
        rows.append({"date": x, "enter_long_sig": 0, "exit_long_sig": int(is_long),
                     "enter_short_sig": 0, "exit_short_sig": int(not is_long)})
    sig = pd.DataFrame(rows)
    if sig.empty:
        sig = pd.DataFrame(columns=["date", "enter_long_sig", "exit_long_sig",
                                    "enter_short_sig", "exit_short_sig"])
    else:
        sig = sig.groupby("date", as_index=False).max().sort_values("date")
    sig.to_csv(path, index=False, date_format="%Y-%m-%d %H:%M:%S%z")


def _write_config(path: Path, *, pair: str, timeframe: str, stake: float,
                  wallet: float, max_open: int, fee: float) -> None:
    cfg = {
        "bot_name": "oos_replay",
        "max_open_trades": max_open,
        "stake_currency": "USDT",
        "stake_amount": stake,
        "tradable_balance_ratio": 0.99,
        "dry_run_wallet": wallet,
        "timeframe": timeframe,
        "fee": fee,
        "trading_mode": "futures",
        "margin_mode": "isolated",
        "cancel_open_orders_on_exit": False,
        "entry_pricing": {
            "price_side": "other",
            "price_last_balance": 0.0,
            "use_order_book": True,
            "check_depth_of_market": {"enabled": False, "bids_to_ask_delta": 1},
        },
        "exit_pricing": {
            "price_side": "other",
            "price_last_balance": 0.0,
            "use_order_book": True,
            "check_depth_of_market": {"enabled": False, "bids_to_ask_delta": 1},
        },
        "unfilledtimeout": {"entry": 10, "exit": 10, "exit_timeout_count": 0, "unit": "minutes"},
        "pairlists": [{"method": "StaticPairList"}],
        "exchange": {
            "name": "binance",
            "pair_whitelist": [pair],
            "pair_blacklist": [],
            # honor HTTP(S)_PROXY env vars in both ccxt sync (requests) and
            # async (aiohttp) clients — required on hosts behind a proxy
            "ccxt_config": {"aiohttp_trust_env": True},
            "ccxt_async_config": {"aiohttp_trust_env": True},
        },
        "dataformat_ohlcv": "feather",
    }
    path.write_text(json.dumps(cfg, indent=2))


def _read_backtest_result(result_dir: Path) -> dict:
    files = sorted(result_dir.glob("backtest-result-*.json"),
                   key=lambda p: p.stat().st_mtime)
    zips = sorted(result_dir.glob("backtest-result-*.zip"),
                  key=lambda p: p.stat().st_mtime)
    if not files and not zips:
        raise FreqtradeReplayError(f"no backtest-result file in {result_dir}")
    if zips and (not files or zips[-1].stat().st_mtime >= files[-1].stat().st_mtime):
        with zipfile.ZipFile(zips[-1]) as zf:
            # the zip bundles the main result plus _config.json / _meta.json
            # and feather sidecars — pick the member carrying "strategy"
            for name in zf.namelist():
                if not name.endswith(".json") or "meta" in name or "config" in name:
                    continue
                data = json.loads(zf.read(name))
                if "strategy" in data:
                    return data
            raise FreqtradeReplayError(f"no strategy result json inside {zips[-1]}")
    return json.loads(files[-1].read_text())


def run_freqtrade_replay(
    df: pd.DataFrame,
    native_trades: list[dict],
    *,
    symbol: str,
    timeframe: str,
    starting_wallet: float = 100_000.0,
    stake_per_trade: float = 1_000.0,
    max_open_trades: int = 5,
    fee: float = 0.0002,
    timeout_s: int = 1200,
    keep_dir: bool = False,
) -> FrameworkRun:
    tf = _TIMEFRAME_MAP.get(timeframe)
    if tf is None:
        raise FreqtradeReplayError(f"unsupported timeframe for freqtrade replay: {timeframe}")
    if shutil.which("freqtrade") is None:
        raise FreqtradeReplayError("freqtrade CLI not found on PATH")

    tmp = Path(tempfile.mkdtemp(prefix="oos_ft_replay_"))
    try:
        userdir = tmp / "user_data"
        (userdir / "strategies").mkdir(parents=True)
        (userdir / "backtest_results").mkdir(parents=True)

        pair = _pair(symbol)
        data_dir = userdir / "data" / "binance" / "futures"
        _write_feather(df, data_dir / f"{_pair_file_stem(symbol)}-{tf}-futures.feather", tf)

        signals_csv = tmp / "signals.csv"
        _write_signals(native_trades, signals_csv)

        (userdir / "strategies" / "SignalReplay.py").write_text(
            _STRATEGY_TEMPLATE % {"timeframe": tf})

        config_path = tmp / "config.json"
        _write_config(config_path, pair=pair, timeframe=tf, stake=stake_per_trade,
                      wallet=starting_wallet, max_open=max_open_trades, fee=fee)

        env = dict(os.environ, REPLAY_SIGNALS_CSV=str(signals_csv))
        cmd = [
            "freqtrade", "backtesting",
            "--userdir", str(userdir),
            "--config", str(config_path),
            "--strategy", "SignalReplay",
            "--backtest-directory", str(userdir / "backtest_results"),
        ]
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout_s, env=env)
        if proc.returncode != 0:
            tail = (proc.stdout + "\n" + proc.stderr).strip().splitlines()[-30:]
            raise FreqtradeReplayError(
                f"freqtrade backtesting exited {proc.returncode}:\n" + "\n".join(tail))

        result = _read_backtest_result(userdir / "backtest_results")
        strat = result["strategy"]["SignalReplay"]

        daily_profit = strat.get("daily_profit") or []
        dates = [pd.Timestamp(d) for d, _ in daily_profit]
        profits = [float(p) for _, p in daily_profit]
        equity_vals = [starting_wallet + v for v in pd.Series(profits).cumsum()]
        equity = pd.Series(equity_vals, index=pd.DatetimeIndex(dates)) if dates else pd.Series(dtype=float)

        trade_pnls = [float(t["profit_ratio"]) for t in strat.get("trades", [])]
        return FrameworkRun(
            framework="freqtrade",
            symbol=symbol,
            equity=equity,
            trade_pnls=trade_pnls,
            trades=[],
        )
    finally:
        if not keep_dir:
            shutil.rmtree(tmp, ignore_errors=True)
