"""venue_adapter_hyperliquid — Hyperliquid DEX perp venue adapter (E4).

Rebuild of the lost ``venue_adapter_hyperliquid_p7exec_007`` module
(.pyc-only).  EIP-712 signing abstraction (injected signer callback,
no private keys), ``action.order`` construction with cloid
discipline, ``orderUpdates`` / ``userFills`` WS parsing, additive
``hyperliquid_intents`` / ``hyperliquid_events`` /
``hyperliquid_acks`` journaling, ack classification incl.
``MARGIN_REJECTED`` / ``RATE_LIMITED``, and a paper transport for
offline tests.
"""
from .venue_adapter_hyperliquid import (
    DEFAULT_HYPERLIQUID_ADAPTER_POLICY,
    DEFAULT_VENUE,
    HL_EXCHANGE_PATH,
    HL_REST_MAINNET,
    HL_REST_TESTNET,
    HL_WS_MAINNET,
    HL_WS_TESTNET,
    IOC_NO_MATCH,
    MARGIN_REJECTED,
    OTHER,
    POST_ONLY_WOULD_CROSS,
    PRICE_BAND,
    RATE_LIMITED,
    SCHEMA_SQL,
    HyperliquidAckSource,
    HyperliquidAdapter,
    HyperliquidAdapterPolicy,
    HyperliquidPaperTransport,
    HyperliquidPaperTransportFillModel,
    HyperliquidSnapshot,
    HyperliquidState,
    HyperliquidStatus,
    SignedEnvelope,
    SignerFn,
    T_ACK_OK,
    T_ACK_REJECT,
    T_BLOCKED,
    T_INTENT_TAGGED,
    T_VALIDATION_FAILED,
    T_WS_UPDATE,
    bootstrap_journal,
    build_eip712_signable,
    build_order_action,
    build_order_wire_order,
    classify_exchange_response,
    derive_cloid,
    is_valid_cloid,
    map_order_update_status,
    normalize_cloid,
    parse_ws_message,
    policy_fingerprint,
    sign_action,
    validate_hl_intent,
)

__all__ = [
    "DEFAULT_HYPERLIQUID_ADAPTER_POLICY",
    "DEFAULT_VENUE",
    "HL_EXCHANGE_PATH",
    "HL_REST_MAINNET",
    "HL_REST_TESTNET",
    "HL_WS_MAINNET",
    "HL_WS_TESTNET",
    "IOC_NO_MATCH",
    "MARGIN_REJECTED",
    "OTHER",
    "POST_ONLY_WOULD_CROSS",
    "PRICE_BAND",
    "RATE_LIMITED",
    "SCHEMA_SQL",
    "HyperliquidAckSource",
    "HyperliquidAdapter",
    "HyperliquidAdapterPolicy",
    "HyperliquidPaperTransport",
    "HyperliquidPaperTransportFillModel",
    "HyperliquidSnapshot",
    "HyperliquidState",
    "HyperliquidStatus",
    "SignedEnvelope",
    "SignerFn",
    "T_ACK_OK",
    "T_ACK_REJECT",
    "T_BLOCKED",
    "T_INTENT_TAGGED",
    "T_VALIDATION_FAILED",
    "T_WS_UPDATE",
    "bootstrap_journal",
    "build_eip712_signable",
    "build_order_action",
    "build_order_wire_order",
    "classify_exchange_response",
    "derive_cloid",
    "is_valid_cloid",
    "map_order_update_status",
    "normalize_cloid",
    "parse_ws_message",
    "policy_fingerprint",
    "sign_action",
    "validate_hl_intent",
]
