"""Mechanical acceptance executor for swarm runs (SMA-36514 / W5-T12).

Reads a run directory's ``manifest.json`` and executes every item's declared
``acceptance.cmd`` sequentially. Each item runs in an isolated ``cwd=run_dir``
with an environment-variable whitelist. Per-item timeouts are clamped at
1800 seconds. Results are aggregated into ``<run_dir>/acceptance.json``.

Exit codes
----------
- ``0``  every item ``passed``
- ``1``  one or more items did not pass (any non-zero exit or timeout)
- ``2``  the manifest itself was missing, unparseable, or failed validation

Trust assumption
----------------
The manifest is treated as *trusted input* because it is generated by the
dispatcher, not by the swarm agents. With that assumption the acceptance
commands may be executed via ``shell=True`` (as the W5-T12 card specifies).
The subprocess environment is restricted to the ``ALLOWED_ENV`` whitelist
below to avoid leaking unrelated secrets into the child's view.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Any

ALLOWED_ENV = ("PATH", "HOME", "LANG", "LC_ALL", "TMPDIR", "SHELL")

MAX_TIMEOUT_SEC = 1800
DEFAULT_TIMEOUT_SEC = 1800
OUTPUT_TAIL_CHARS = 4000

SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")


# ---------------------------------------------------------------------------
# Manifest validation (inline dict shape; jsonschema is used opportunistically
# when ``manifest.schema.json`` happens to live next to this file — that file
# is produced by the T11a card in the same series).
# ---------------------------------------------------------------------------

def _validate_manifest_shape(manifest: Any) -> None:
    """Raise ``ValueError`` if ``manifest`` is not a well-shaped swarm manifest.

    Performs the structural checks that every T12 manifest must satisfy,
    independent of whether a JSON Schema file is present in the workspace.
    """
    if not isinstance(manifest, dict):
        raise ValueError("manifest root must be a JSON object")
    for key in ("run_id", "created_at", "items"):
        if key not in manifest:
            raise ValueError(f"manifest missing required field: {key!r}")
    if not isinstance(manifest["items"], list) or not manifest["items"]:
        raise ValueError("manifest.items must be a non-empty list")
    for i, item in enumerate(manifest["items"]):
        if not isinstance(item, dict):
            raise ValueError(f"items[{i}] must be an object")
        slug = item.get("slug")
        if not isinstance(slug, str) or not SLUG_RE.match(slug):
            raise ValueError(
                f"items[{i}].slug {slug!r} does not match "
                f"{SLUG_RE.pattern!r}"
            )
        files = item.get("files")
        if not isinstance(files, list) or not files:
            raise ValueError(f"items[{i}].files must be a non-empty list")
        for j, p in enumerate(files):
            if not isinstance(p, str):
                raise ValueError(f"items[{i}].files[{j}] must be a string")
            if os.path.isabs(p):
                raise ValueError(
                    f"items[{i}].files[{j}] {p!r} must be relative"
                )
            # Reject any path that escapes the run dir via '..'.
            parts = Path(p).parts
            if ".." in parts:
                raise ValueError(
                    f"items[{i}].files[{j}] {p!r} contains '..'"
                )
        acc = item.get("acceptance")
        if not isinstance(acc, dict) or "cmd" not in acc:
            raise ValueError(
                f"items[{i}].acceptance.cmd is required"
            )
        if not isinstance(acc["cmd"], str) or not acc["cmd"].strip():
            raise ValueError(f"items[{i}].acceptance.cmd must be non-empty")
        timeout = acc.get("timeout_sec")
        if timeout is not None and (
            not isinstance(timeout, int) or timeout <= 0
        ):
            raise ValueError(
                f"items[{i}].acceptance.timeout_sec must be a positive int"
            )


def _try_jsonschema_validate(manifest: dict) -> tuple[bool, str | None]:
    """If ``manifest.schema.json`` exists next to this module and ``jsonschema``
    is importable, run it. Return ``(True, None)`` on success, or
    ``(False, err_msg)`` on failure. When the schema file is absent, return
    ``(True, None)`` (the inline shape check above is the sole gate)."""
    schema_path = Path(__file__).resolve().parent / "manifest.schema.json"
    if not schema_path.exists():
        return True, None
    try:
        import jsonschema  # type: ignore[import-not-found]
    except Exception:
        return True, None
    try:
        schema = json.loads(schema_path.read_text())
        jsonschema.validate(manifest, schema)
        return True, None
    except Exception as e:
        return False, str(e)


# ---------------------------------------------------------------------------
# Manifest loading
# ---------------------------------------------------------------------------

def _load_manifest(run_dir: Path) -> tuple[dict | None, str | None]:
    """Return ``(manifest, error_message)``. Exactly one is non-None."""
    manifest_path = run_dir / "manifest.json"
    if not manifest_path.exists():
        return None, f"manifest not found: {manifest_path}"
    try:
        text = manifest_path.read_text()
    except OSError as e:
        return None, f"cannot read manifest: {e}"
    try:
        manifest = json.loads(text)
    except json.JSONDecodeError as e:
        return None, f"manifest JSON parse error: {e}"
    if not isinstance(manifest, dict):
        return None, "manifest root must be a JSON object"
    try:
        _validate_manifest_shape(manifest)
    except ValueError as e:
        return None, f"manifest validation error: {e}"
    ok, err = _try_jsonschema_validate(manifest)
    if not ok:
        return None, f"manifest schema validation error: {err}"
    return manifest, None


# ---------------------------------------------------------------------------
# Acceptance execution
# ---------------------------------------------------------------------------

def _decode(b: bytes | str | None) -> str:
    if b is None:
        return ""
    if isinstance(b, str):
        return b
    return b.decode("utf-8", errors="replace")


def _child_env() -> dict[str, str]:
    return {k: v for k, v in os.environ.items() if k in ALLOWED_ENV}


def _now_iso() -> str:
    return datetime.now().astimezone().isoformat(timespec="seconds")


def _resolve_timeout(
    item: dict,
    timeout_override: int | None,
) -> int:
    raw = item.get("acceptance", {}).get(
        "timeout_sec", DEFAULT_TIMEOUT_SEC
    )
    if timeout_override is not None:
        raw = timeout_override
    # Clamp to (0, MAX_TIMEOUT_SEC].
    try:
        n = int(raw)
    except (TypeError, ValueError):
        n = DEFAULT_TIMEOUT_SEC
    return max(1, min(n, MAX_TIMEOUT_SEC))


def run_acceptance(
    run_dir: str | Path,
    timeout_override: int | None = None,
) -> int:
    """Run acceptance for the swarm run at ``run_dir``.

    Returns the process exit code (0 = all passed, 1 = any failure/timeout,
    2 = manifest missing or invalid). Results, when execution actually
    started, are written to ``<run_dir>/acceptance.json``.
    """
    run_path = Path(run_dir).resolve()
    manifest, err = _load_manifest(run_path)
    if err is not None:
        print(f"ERROR: {err}", file=sys.stderr)
        return 2

    child_env = _child_env()
    results: list[dict[str, Any]] = []
    any_failed = False

    for item in manifest["items"]:
        slug = item["slug"]
        cmd = item["acceptance"]["cmd"]
        timeout = _resolve_timeout(item, timeout_override)
        t0 = time.monotonic()
        try:
            proc = subprocess.run(
                cmd,
                shell=True,
                cwd=str(run_path),
                env=child_env,
                capture_output=True,
                text=True,
                timeout=timeout,
            )
            elapsed = time.monotonic() - t0
            status = "passed" if proc.returncode == 0 else "failed"
            tail = (proc.stdout + proc.stderr)[-OUTPUT_TAIL_CHARS:]
            exit_code = proc.returncode
            duration = round(elapsed, 3)
            if status == "passed":
                print(f"PASS {slug} ({elapsed:.1f}s)")
            else:
                print(f"FAIL {slug} exit={exit_code}")
                any_failed = True
            results.append({
                "slug": slug,
                "cmd": cmd,
                "status": status,
                "exit_code": exit_code,
                "duration_sec": duration,
                "output_tail": tail,
            })
        except subprocess.TimeoutExpired as e:
            elapsed = time.monotonic() - t0
            stdout_text = _decode(getattr(e, "stdout", None))
            stderr_text = _decode(getattr(e, "stderr", None))
            tail = (stdout_text + stderr_text)[-OUTPUT_TAIL_CHARS:]
            print(f"TIMEOUT {slug} (>{timeout}s)")
            any_failed = True
            results.append({
                "slug": slug,
                "cmd": cmd,
                "status": "timeout",
                "exit_code": -1,
                "duration_sec": round(elapsed, 3),
                "output_tail": tail,
            })

    summary = {
        "run_id": manifest.get("run_id"),
        "ran_at": _now_iso(),
        "results": results,
        "overall": "failed" if any_failed else "passed",
    }

    out_path = run_path / "acceptance.json"
    out_path.write_text(json.dumps(summary, indent=2) + "\n")
    return 1 if any_failed else 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _parse_argv(argv: list[str] | None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="accept.py",
        description=(
            "Run mechanical acceptance for a swarm run directory. "
            "Reads <run_dir>/manifest.json, runs each item's "
            "acceptance.cmd sequentially, and writes "
            "<run_dir>/acceptance.json with per-item results."
        ),
    )
    p.add_argument("run_dir", help="Swarm run directory (contains manifest.json)")
    p.add_argument(
        "--timeout-sec",
        type=int,
        default=None,
        help=(
            "Override per-item timeout in seconds (clamped to 1..1800). "
            "When set, applies to every item."
        ),
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_argv(argv)
    return run_acceptance(args.run_dir, timeout_override=args.timeout_sec)


if __name__ == "__main__":
    raise SystemExit(main())