"""Generate a contract-v2-compliant strategy directory.

W3-T10 (wave 2). Single CLI that scaffolds a new strategy under
``<quant-loop>/strategies/<name>/`` (or anywhere via ``--out-root``)
with the SPEC, config, signal stub, and a self-check contract test:

::

    python3 -m _shared.templates.scaffold <name> \\
        --symbols BTCUSDT,ETHUSDT --tf 15m

The generated ``tests/test_contract.py`` passes out of the box:
``check_contract()`` runs the stub on deterministic synthetic bars
built from ``DEFAULT_CONFIG`` and validates the ``[Trade]`` return.

Failure modes (all exit 2 unless noted):

  * invalid name (not ``^[a-z][a-z0-9_]*$``)            -> argparse exit 2
  * target directory exists and is non-empty            -> SystemExit 2
  * spec template missing                               -> RuntimeError
"""
from __future__ import annotations

import argparse
import re
import sys
from datetime import date as _date
from pathlib import Path
from typing import Sequence


_ROOT = Path(__file__).resolve().parents[2]  # quant-loop/
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

_DEFAULT_OUT_ROOT = _ROOT / "strategies"
_TEMPLATE_DIR = Path(__file__).resolve().parent
_SPEC_TEMPLATE = _TEMPLATE_DIR / "SPEC_TEMPLATE.md"

# Strategy module name: lowercase, leading letter, then [a-z0-9_]*.
# Matches common quant-loop strategy directory conventions
# (e.g. ``loid_vpvr_confluence_20260717``).
_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")

# Inline-cost scanner literals (see ``_shared/execution/check_inline_costs.py``).
# Used only for the docstring sanity check in the generated strategy module;
# the literal itself appears nowhere in scaffold.py.
_INLINE_COST_LITERALS = ("0.0004", "0.0008", "0.0011", "0.0022", "0.0024")


# ---------------------------------------------------------------------------
# Strategy file templates (module-level so tests can introspect them).
# ---------------------------------------------------------------------------

_STRATEGY_PY = '''"""{name} — contract v2 strategy stub. See SPEC.md.

Generated by ``_shared.templates.scaffold`` on {date}. The skeleton below
is a *pass-the-contract* stub: ``generate_signals`` returns an empty list,
which is structurally valid (no trades, no errors). Replace the body with
real signals once the SPEC hypothesis is locked in.

Rules (strategy_contract_v2):

* Signal layer only — equity / metrics are computed by the runner.
* Indicators must come from ``_shared/indicators/`` — no inline
  re-implementations.
* No local data copies — bars are handed in by
  ``_shared.templates.run_strategy`` / ``_shared.data_loader``.
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Any, Dict, List

import pandas as pd

# Resolve the quant-loop repo by walking up from this file looking for
# ``_shared/run_backtest.py``. Works regardless of where the scaffold
# was generated (e.g. ``/tmp/scaffold_accept/...`` for acceptance runs).
_p = Path(__file__).resolve()
for _a in _p.parents:
    if (_a / "_shared" / "run_backtest.py").is_file():
        if str(_a) not in sys.path:
            sys.path.insert(0, str(_a))
        break

from _shared.run_backtest import Trade  # noqa: E402


DEFAULT_CONFIG: Dict[str, Any] = {{
    "symbols": {symbols_json},
    "primary_symbol": {primary_json},
    "timeframe": {tf_json},
    "size_fraction": 0.95,
}}


def generate_signals(
    bars: Dict[str, pd.DataFrame],
    config: Dict[str, Any],
) -> List[Trade]:
    """Contract v2 entry point: bars dict + config -> list[Trade].

    The stub below returns ``[]`` so the contract check passes with no
    side effects. Replace with the SPEC's actual hypothesis:

        1. Compute indicators from ``bars`` (use ``_shared/indicators/``)
        2. Build a long/short signal per bar on the primary symbol
        3. Wire entries/exits into ``Trade(entry_ts, exit_ts, direction,
           size_fraction)``
    """
    return []


__all__ = ["DEFAULT_CONFIG", "generate_signals"]
'''


_TEST_CONTRACT_PY = '''"""Out-of-the-box contract test for {name}.

Generated by ``_shared.templates.scaffold`` on {date}. Runs
``strategy_contract_v2.check_contract()`` on this directory's
``strategy.py`` against deterministic synthetic bars.

This is the *cheap* gate (signature + synthetic smoke run, ~0.3s). It
does NOT prove profitability — that is the job of the G1–G7 backtest
gates. Once a real signal is wired in, the contract test still
catches interface regressions automatically.
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

# Same ancestor-search bootstrap as strategy.py: works under any
# layout (scaffolded to /tmp or under strategies/).
_p = Path(__file__).resolve()
for _a in _p.parents:
    if (_a / "_shared" / "run_backtest.py").is_file():
        if str(_a) not in sys.path:
            sys.path.insert(0, str(_a))
        break

from _shared.templates.strategy_contract_v2 import check_contract  # noqa: E402


def test_contract_v2_synthetic_smoke():
    """strategy.py exposes generate_signals(bars, config) -> list[Trade].

    ``check_contract()`` builds deterministic synthetic bars from the
    module's ``DEFAULT_CONFIG`` and validates the return is a list of
    ``Trade`` on the primary symbol's bar index.
    """
    strategy_path = Path(__file__).resolve().parents[1] / "strategy.py"
    spec = importlib.util.spec_from_file_location("strategy", strategy_path)
    assert spec is not None and spec.loader is not None, (
        f"cannot load strategy module from {{strategy_path}}"
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    report = check_contract(mod)
    assert report["ok"] is True
'''


_README_MD = """# {name}

Generated by `_shared.templates.scaffold` on {date}.

* **Symbols**: `{symbols}` (primary = `{primary_symbol}`)
* **Timeframe**: `{tf}`
* **SPEC**: see [SPEC.md](SPEC.md)
* **Contract test**: `python3 -m pytest tests/ -q`

Run the strategy end-to-end:

```
python3 -m _shared.templates.run_strategy strategy.py \\
    --config config.json --bars-dir data/perp_{tf} \\
    --symbol {primary_symbol}
```
"""


# ---------------------------------------------------------------------------
# CLI / public API.
# ---------------------------------------------------------------------------


def _parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="scaffold",
        description=__doc__.splitlines()[0] if __doc__ else None,
    )
    parser.add_argument(
        "name",
        help=(
            "Strategy directory name. Must match ``^[a-z][a-z0-9_]*$`` "
            "(e.g. ``loid_vpvr_confluence_20260717``)."
        ),
    )
    parser.add_argument(
        "--symbols",
        default="BTCUSDT",
        help="Comma-separated symbol list (default: BTCUSDT).",
    )
    parser.add_argument(
        "--tf",
        default="15m",
        help="Primary timeframe (default: 15m).",
    )
    parser.add_argument(
        "--out-root",
        default=str(_DEFAULT_OUT_ROOT),
        help=(
            "Parent directory for the new strategy directory "
            f"(default: {_DEFAULT_OUT_ROOT})."
        ),
    )
    return parser.parse_args(argv)


def _validate_name(name: str) -> None:
    if not _NAME_RE.match(name):
        print(
            f"error: invalid name {name!r}; must match {_NAME_RE.pattern!r}\n"
            "  (lowercase letters / digits / underscores; must start "
            "with a letter; example: loid_vpvr_confluence_20260717)",
            file=sys.stderr,
        )
        raise SystemExit(2)


def _parse_symbols(raw: str) -> list[str]:
    out = [s.strip() for s in raw.split(",") if s.strip()]
    if not out:
        print("error: --symbols must contain at least one symbol", file=sys.stderr)
        raise SystemExit(2)
    return out


def _render_spec(spec_text: str, *, name: str, symbols: list[str],
                 tf: str, today: str) -> str:
    return spec_text.format(
        strategy_name=name,
        symbols=", ".join(symbols),
        tf=tf,
        date=today,
    )


def _render_strategy(*, name: str, symbols: list[str], tf: str,
                     today: str) -> str:
    import json as _json
    return _STRATEGY_PY.format(
        name=name,
        date=today,
        symbols_json=_json.dumps(symbols),
        primary_json=_json.dumps(symbols[0]),
        tf_json=_json.dumps(tf),
    )


def _render_test_contract(*, name: str, today: str) -> str:
    return _TEST_CONTRACT_PY.format(name=name, date=today)


def _render_readme(*, name: str, symbols: list[str], tf: str,
                   today: str) -> str:
    return _README_MD.format(
        name=name,
        symbols=", ".join(symbols),
        primary_symbol=symbols[0],
        tf=tf,
        date=today,
    )


def _render_config(*, symbols: list[str], tf: str) -> str:
    import json as _json
    return _json.dumps(
        {
            "symbols": symbols,
            "primary_symbol": symbols[0],
            "timeframe": tf,
            "size_fraction": 0.95,
        },
        indent=2,
    ) + "\n"


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _check_empty(target: Path) -> None:
    """Refuse to scaffold over an existing non-empty directory.

    Exit code 2 matches the test card's contract (``SystemExit(2)`` /
    ``FileExistsError`` — we pick ``SystemExit(2)`` so it is observable
    from shell as a clean exit code, not a stack trace). The error
    message goes to stderr so a script can capture it separately from
    the stdout target-path line on success.
    """
    if target.exists():
        if not target.is_dir():
            print(
                f"error: {target} exists and is not a directory (refusing to "
                "overwrite)",
                file=sys.stderr,
            )
            raise SystemExit(2)
        if any(target.iterdir()):
            print(
                f"error: {target} exists and is non-empty "
                "(refusing to overwrite; remove it or pick a new name)",
                file=sys.stderr,
            )
            raise SystemExit(2)


def scaffold(
    name: str,
    symbols: Sequence[str],
    tf: str = "15m",
    out_root: str | Path = _DEFAULT_OUT_ROOT,
    *,
    today: str | None = None,
    spec_template_path: str | Path | None = None,
) -> Path:
    """Generate the strategy directory at ``<out_root>/<name>``.

    Returns the absolute path to the generated directory.
    Raises ``SystemExit(2)`` on validation errors (existing non-empty
    directory, invalid name, etc.).
    """
    _validate_name(name)
    symbols_list = list(symbols)
    if not symbols_list:
        print("error: symbols list must be non-empty", file=sys.stderr)
        raise SystemExit(2)
    target = Path(out_root).resolve() / name
    _check_empty(target)

    today = today or _date.today().isoformat()
    template = Path(spec_template_path) if spec_template_path else _SPEC_TEMPLATE
    if not template.is_file():
        raise RuntimeError(
            f"SPEC template not found at {template}; cannot scaffold without it"
        )
    spec_text = template.read_text(encoding="utf-8")
    spec_rendered = _render_spec(
        spec_text, name=name, symbols=symbols_list, tf=tf, today=today
    )

    target.mkdir(parents=True, exist_ok=True)
    _write(target / "SPEC.md", spec_rendered)
    _write(
        target / "config.json",
        _render_config(symbols=symbols_list, tf=tf),
    )
    _write(
        target / "strategy.py",
        _render_strategy(
            name=name, symbols=symbols_list, tf=tf, today=today
        ),
    )
    _write(
        target / "tests" / "test_contract.py",
        _render_test_contract(name=name, today=today),
    )
    _write(target / "results" / ".gitkeep", "")
    _write(
        target / "README.md",
        _render_readme(
            name=name, symbols=symbols_list, tf=tf, today=today
        ),
    )
    return target


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(argv)
    symbols = _parse_symbols(args.symbols)
    target = scaffold(
        name=args.name,
        symbols=symbols,
        tf=args.tf,
        out_root=args.out_root,
    )
    print(str(target))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
