#!/usr/bin/env python3
"""200-metric trading infrastructure evaluation framework.

Defines the metric taxonomy and generates the leaderboard HTML.
Scores: 0 = none, 1 = partial, 2 = full.
"""

CATEGORIES = {
    "A": "策略研发 Strategy R&D",
    "B": "回测引擎 Backtest Engine",
    "C": "做市能力 Market Making",
    "D": "风险管理 Risk Management",
    "E": "执行与订单 Execution",
    "F": "数据层 Data Layer",
    "G": "验证与证伪 Validation & Falsification",
    "H": "实盘运营 Live Operations",
    "I": "组合管理 Portfolio",
    "J": "工程质量 Code Quality",
}

METRICS = [
    # ---- A. 策略研发 (20) ----
    ("A1", "A", "信号接口标准化", "统一 generate_signals 契约"),
    ("A2", "A", "策略参数外部化", "config 与代码分离"),
    ("A3", "A", "多时间框架信号", "MTF 原生支持"),
    ("A4", "A", "跨截面/组合信号", "pairs/rank 类策略支持"),
    ("A5", "A", "内置因子库", "可复用因子组件"),
    ("A6", "A", "技术指标库覆盖", "TA 指标数量与质量"),
    ("A7", "A", "自定义指标注册", "指标插件机制"),
    ("A8", "A", "信号合成器", "多信号加权组合"),
    ("A9", "A", "参数网格扫描", "grid search 引擎"),
    ("A10", "A", "参数进化优化", "genetic/贝叶斯优化"),
    ("A11", "A", "策略模板库", "内置可运行策略模板"),
    ("A12", "A", "策略版本管理", "策略迭代可追溯"),
    ("A13", "A", "结果持久化台账", "results ledger"),
    ("A14", "A", "策略间信号共享", "信号总线/共享特征"),
    ("A15", "A", "策略热重载", "不重启改参数"),
    ("A16", "A", "ML 模型接入", "ML pipeline 集成点"),
    ("A17", "A", "特征工程管线", "feature pipeline"),
    ("A18", "A", "标签工程", "triple-barrier 等高级标签"),
    ("A19", "A", "元标签", "meta-labeling 支持"),
    ("A20", "A", "研究文档关联", "策略-研究笔记联动"),
    # ---- B. 回测引擎 (20) ----
    ("B1", "B", "事件驱动回测", "event-driven loop"),
    ("B2", "B", "向量化回测", "vectorized backtest"),
    ("B3", "B", "逐笔 tick 回测", "trade-by-trade replay"),
    ("B4", "B", "L2 订单簿回放", "order book replay"),
    ("B5", "B", "部分成交模拟", "partial fills"),
    ("B6", "B", "队列位置建模", "queue position in backtest"),
    ("B7", "B", "延迟建模", "latency simulation"),
    ("B8", "B", "固定滑点模型", "fixed slippage"),
    ("B9", "B", "冲击成本滑点", "sqrt-impact slippage"),
    ("B10", "B", "实测校准滑点", "empirically calibrated"),
    ("B11", "B", "maker/taker 费率分离", "asymmetric fees"),
    ("B12", "B", "资金费率处理", "funding in perp backtest"),
    ("B13", "B", "强平模拟", "liquidation simulation"),
    ("B14", "B", "多标的组合回测", "multi-symbol portfolio"),
    ("B15", "B", "多策略组合回测", "multi-strategy portfolio"),
    ("B16", "B", "回测速度", ">100K bars/s"),
    ("B17", "B", "回测确定性", "同输入同输出"),
    ("B18", "B", "防前视偏差哨兵", "look-ahead sentinels"),
    ("B19", "B", "回测-实盘同代码", "shared code path"),
    ("B20", "B", "回测审计追踪", "audit trail"),
    # ---- C. 做市能力 (20) ----
    ("C1", "C", "连续双向报价", "continuous two-sided quoting"),
    ("C2", "C", "公允价值估计", "microprice/VWAP/POC"),
    ("C3", "C", "库存跟踪", "inventory tracking"),
    ("C4", "C", "库存偏斜", "inventory skew"),
    ("C5", "C", "A-S 预留价格", "Avellaneda-Stoikov reservation price"),
    ("C6", "C", "A-S 最优 spread", "analytical optimal spread"),
    ("C7", "C", "多层报价", "multi-level ladder"),
    ("C8", "C", "队列位置 fill 概率", "queue fill probability model"),
    ("C9", "C", "逆向选择 fill 响应", "post-fill quote adjustment"),
    ("C10", "C", "逆向选择成本实测", "empirical AS calibration"),
    ("C11", "C", "Bayesian 信念更新", "fill → fair value update"),
    ("C12", "C", "Sweep 检测与冷却", "sweep detection + cooldown"),
    ("C13", "C", "报价 tick 对齐", "tick alignment"),
    ("C14", "C", "报价频率控制", "quote rate throttling"),
    ("C15", "C", "cancel-replace 逻辑", "amend vs cancel-replace"),
    ("C16", "C", "单边报价", "one-sided at inventory limit"),
    ("C17", "C", "做市专属指标", "fill_rate/maker_ratio/markout"),
    ("C18", "C", "做市回测模拟器", "aggTrades fill simulation"),
    ("C19", "C", "跨所价差做市", "cross-venue quoting"),
    ("C20", "C", "网格做市", "grid quoting"),
    # ---- D. 风险管理 (20) ----
    ("D1", "D", "波动率目标仓位", "vol targeting"),
    ("D2", "D", "Kelly 仓位", "Kelly criterion sizing"),
    ("D3", "D", "流动性上限仓位", "ADV/depth/participation caps"),
    ("D4", "D", "冲击成本感知仓位", "impact-aware sizing"),
    ("D5", "D", "知情交易感知仓位", "VPIN-aware sizing"),
    ("D6", "D", "单笔止损", "per-trade stop loss"),
    ("D7", "D", "单笔止盈", "per-trade take profit"),
    ("D8", "D", "时间止损", "time stop"),
    ("D9", "D", "回撤熔断", "drawdown kill-switch"),
    ("D10", "D", "滚动 Sharpe 熔断", "rolling Sharpe floor"),
    ("D11", "D", "盈亏比熔断", "profit-factor floor"),
    ("D12", "D", "VaR 计算", "value at risk"),
    ("D13", "D", "CVaR/ES 计算", "expected shortfall"),
    ("D14", "D", "胖尾修正", "Cornish-Fisher adjustment"),
    ("D15", "D", "连亏统计", "consecutive loss tracking"),
    ("D16", "D", "压力测试场景库", "stress scenario library"),
    ("D17", "D", "保证金/清算保护", "liquidation guard"),
    ("D18", "D", "风险预算分配", "risk budgeting"),
    ("D19", "D", "实时风险监控", "live risk dashboard"),
    ("D20", "D", "风险事件审计", "risk event audit log"),
    # ---- E. 执行与订单 (20) ----
    ("E1", "E", "可插拔 adapter 框架", "pluggable venue adapters"),
    ("E2", "E", "Binance 现货 adapter", "spot venue support"),
    ("E3", "E", "Binance 永续 adapter", "perp venue support"),
    ("E4", "E", "DEX adapter", "Hyperliquid/dYdX support"),
    ("E5", "E", "限价单", "limit orders"),
    ("E6", "E", "市价单", "market orders"),
    ("E7", "E", "post-only 单", "maker-only orders"),
    ("E8", "E", "IOC/FOK 单", "immediate-or-cancel / fill-or-kill"),
    ("E9", "E", "订单生命周期状态机", "order state machine"),
    ("E10", "E", "幂等订单 ID", "idempotent client order IDs"),
    ("E11", "E", "订单-成交关联", "order-to-fill linker"),
    ("E12", "E", "部分成交聚合", "partial fill accumulation"),
    ("E13", "E", "影子账本", "shadow book"),
    ("E14", "E", "实盘对账", "venue-truth reconciliation"),
    ("E15", "E", "迟到成交拒绝取证", "late-fill rejection + forensics"),
    ("E16", "E", "WS 私有频道", "private order updates"),
    ("E17", "E", "WS 断线重连", "auto reconnect"),
    ("E18", "E", "速率限制管理", "rate limit handling"),
    ("E19", "E", "纸交易模式", "paper trading"),
    ("E20", "E", "执行质量分析", "TCA / slippage attribution"),
    # ---- F. 数据层 (20) ----
    ("F1", "F", "K 线下载器", "OHLCV downloader"),
    ("F2", "F", "逐笔下载器", "aggTrades downloader"),
    ("F3", "F", "现货数据覆盖", "spot coverage"),
    ("F4", "F", "永续数据覆盖", "perp coverage"),
    ("F5", "F", "资金费率数据", "funding rates"),
    ("F6", "F", "强平数据", "liquidation data"),
    ("F7", "F", "OI 数据", "open interest"),
    ("F8", "F", "多空比数据", "long/short ratio"),
    ("F9", "F", "跨所同标的数据", "cross-venue same symbol"),
    ("F10", "F", "列式存储", "parquet/columnar"),
    ("F11", "F", "数据分区", "hive partitioning"),
    ("F12", "F", "数据清单溯源", "manifest/provenance"),
    ("F13", "F", "数据新鲜度监控", "freshness monitoring"),
    ("F14", "F", "数据质量检查", "gap/anomaly checks"),
    ("F15", "F", "数据回填修复", "backfill tooling"),
    ("F16", "F", "实时数据流接入", "live stream ingestion"),
    ("F17", "F", "数据快照回放", "snapshot replay"),
    ("F18", "F", "特征存储", "feature store"),
    ("F19", "F", "数据版本管理", "data versioning"),
    ("F20", "F", "统一数据访问层", "unified data API"),
    # ---- G. 验证与证伪 (20) ----
    ("G1", "G", "样本外验证", "OOS validation"),
    ("G2", "G", "walk-forward", "walk-forward analysis"),
    ("G3", "G", "K-fold CV", "cross validation"),
    ("G4", "G", "Purged K-fold", "purge at boundaries"),
    ("G5", "G", "Embargo 隔离带", "embargo periods"),
    ("G6", "G", "CPCV", "combinatorial purged CV"),
    ("G7", "G", "多重检验校正", "Bonferroni 等"),
    ("G8", "G", "Deflated Sharpe", "Bailey-LdP DSR"),
    ("G9", "G", "Bootstrap 置信区间", "bootstrap CI"),
    ("G10", "G", "费震动压力回放", "fee-shock replay"),
    ("G11", "G", "预注册 kill 条件", "pre-registered falsification"),
    ("G12", "G", "家族穷竭规则", "family exhaustion rule"),
    ("G13", "G", "诚实 KILL 台账", "honest negative-results ledger"),
    ("G14", "G", "跨框架交叉验证", "multi-engine cross-validation"),
    ("G15", "G", "成本上限证伪", "cost-cap falsification"),
    ("G16", "G", "前视偏差审计", "look-ahead audit"),
    ("G17", "G", "不变量回归测试", "business invariant tests"),
    ("G18", "G", "参数敏感性分析", "parameter sensitivity"),
    ("G19", "G", "逐年分解验证", "per-year walk-forward breakdown"),
    ("G20", "G", "信号衰减监控", "alpha decay monitoring"),
    # ---- H. 实盘运营 (20) ----
    ("H1", "H", "实盘主循环 runner", "live runner"),
    ("H2", "H", "状态持久化恢复", "idempotent resume"),
    ("H3", "H", "多层次 kill-switch", "multi-level kill switches"),
    ("H4", "H", "优雅停机", "graceful drain"),
    ("H5", "H", "异常告警", "alerting"),
    ("H6", "H", "结构化日志", "structured logging"),
    ("H7", "H", "指标导出", "Prometheus/metrics export"),
    ("H8", "H", "配置热更新", "hot config reload"),
    ("H9", "H", "多策略并行", "multi-strategy concurrent"),
    ("H10", "H", "资源隔离", "resource isolation"),
    ("H11", "H", "部署脚本", "deployment automation"),
    ("H12", "H", "环境分离", "testnet/mainnet separation"),
    ("H13", "H", "API key 管理", "secrets management"),
    ("H14", "H", "运行时长监控", "uptime monitoring"),
    ("H15", "H", "心跳探测", "heartbeat/liveness"),
    ("H16", "H", "崩溃自动重启", "auto restart"),
    ("H17", "H", "版本回滚", "rollback support"),
    ("H18", "H", "实盘 PnL 归因", "live PnL attribution"),
    ("H19", "H", "实盘-回测偏差监控", "live-backtest drift"),
    ("H20", "H", "运行审计追踪", "operations audit trail"),
    # ---- I. 组合管理 (20) ----
    ("I1", "I", "多策略权重分配", "strategy weight allocation"),
    ("I2", "I", "相关性矩阵", "correlation matrix"),
    ("I3", "I", "多样化比率", "diversification ratio"),
    ("I4", "I", "ERC 等风险贡献", "equal risk contribution"),
    ("I5", "I", "动态再平衡", "dynamic rebalancing"),
    ("I6", "I", "危机相关性检测", "crisis correlation detection"),
    ("I7", "I", "组合 VaR", "portfolio VaR"),
    ("I8", "I", "组合 CVaR", "portfolio CVaR"),
    ("I9", "I", "组合压力测试", "portfolio stress test"),
    ("I10", "I", "组合回撤归因", "portfolio DD attribution"),
    ("I11", "I", "策略间资本共享", "shared capital pool"),
    ("I12", "I", "策略独立账户视图", "per-strategy account view"),
    ("I13", "I", "组合敞口限制", "portfolio exposure limits"),
    ("I14", "I", "集中度限制", "concentration limits"),
    ("I15", "I", "组合性能归因", "Brinson-style attribution"),
    ("I16", "I", "策略加入/退出", "strategy onboarding/offboarding"),
    ("I17", "I", "组合基准对比", "benchmark comparison"),
    ("I18", "I", "组合再优化调度", "re-optimization schedule"),
    ("I19", "I", "组合状态快照", "portfolio snapshots"),
    ("I20", "I", "组合报告生成", "portfolio reporting"),
    # ---- J. 工程质量 (20) ----
    ("J1", "J", "测试覆盖率", ">50% coverage"),
    ("J2", "J", "单元测试", "module-level tests"),
    ("J3", "J", "集成测试", "end-to-end tests"),
    ("J4", "J", "回归测试", "regression tests"),
    ("J5", "J", "不变量测试", "business invariant tests"),
    ("J6", "J", "类型标注覆盖", "type hints"),
    ("J7", "J", "不可变数据结构", "frozen dataclasses"),
    ("J8", "J", "纯函数核心", "pure core logic"),
    ("J9", "J", "模块解耦", "low coupling"),
    ("J10", "J", "文档字符串覆盖", "docstring coverage"),
    ("J11", "J", "架构文档", "architecture docs"),
    ("J12", "J", "策略开发文档", "strategy dev docs"),
    ("J13", "J", "API 文档", "API reference docs"),
    ("J14", "J", "示例代码", "runnable examples"),
    ("J15", "J", "CI/CD 流水线", "continuous integration"),
    ("J16", "J", "代码风格统一", "linter enforcement"),
    ("J17", "J", "依赖锁定", "lockfile"),
    ("J18", "J", "性能剖析工具", "profiling tooling"),
    ("J19", "J", "代码审查流程", "review process"),
    ("J20", "J", "社区/贡献生态", "community & contributors"),
]

assert len(METRICS) == 200, f"expected 200, got {len(METRICS)}"

# Scores: 0 = none, 1 = partial, 2 = full
# multica self-assessment (verified against codebase 2026-08-02)
MULTICA = {
    # A 策略研发
    "A1": 2, "A2": 2, "A3": 2, "A4": 2, "A5": 1, "A6": 1, "A7": 0, "A8": 0,
    "A9": 2, "A10": 2, "A11": 1, "A12": 1, "A13": 2, "A14": 0, "A15": 0,
    "A16": 0, "A17": 1, "A18": 0, "A19": 0, "A20": 1,
    # B 回测引擎
    "B1": 2, "B2": 1, "B3": 2, "B4": 0, "B5": 0, "B6": 1, "B7": 0, "B8": 2,
    "B9": 2, "B10": 2, "B11": 2, "B12": 2, "B13": 0, "B14": 2, "B15": 1,
    "B16": 1, "B17": 2, "B18": 2, "B19": 1, "B20": 2,
    # C 做市能力
    "C1": 2, "C2": 2, "C3": 2, "C4": 2, "C5": 2, "C6": 2, "C7": 2, "C8": 2,
    "C9": 2, "C10": 2, "C11": 2, "C12": 2, "C13": 2, "C14": 0, "C15": 0,
    "C16": 2, "C17": 2, "C18": 2, "C19": 0, "C20": 2,
    # D 风险管理
    "D1": 2, "D2": 2, "D3": 2, "D4": 2, "D5": 2, "D6": 2, "D7": 2, "D8": 2,
    "D9": 2, "D10": 2, "D11": 2, "D12": 2, "D13": 2, "D14": 2, "D15": 2,
    "D16": 2, "D17": 2, "D18": 1, "D19": 0, "D20": 1,
    # E 执行与订单
    "E1": 2, "E2": 0, "E3": 2, "E4": 1, "E5": 2, "E6": 2, "E7": 1, "E8": 0,
    "E9": 2, "E10": 2, "E11": 2, "E12": 2, "E13": 2, "E14": 2, "E15": 2,
    "E16": 2, "E17": 1, "E18": 1, "E19": 2, "E20": 1,
    # F 数据层
    "F1": 2, "F2": 2, "F3": 2, "F4": 2, "F5": 2, "F6": 1, "F7": 1, "F8": 1,
    "F9": 2, "F10": 2, "F11": 2, "F12": 2, "F13": 1, "F14": 1, "F15": 1,
    "F16": 1, "F17": 0, "F18": 0, "F19": 0, "F20": 1,
    # G 验证与证伪
    "G1": 2, "G2": 2, "G3": 2, "G4": 2, "G5": 2, "G6": 2, "G7": 2, "G8": 2,
    "G9": 2, "G10": 2, "G11": 2, "G12": 2, "G13": 2, "G14": 2, "G15": 2,
    "G16": 2, "G17": 2, "G18": 1, "G19": 2, "G20": 1,
    # H 实盘运营
    "H1": 2, "H2": 2, "H3": 2, "H4": 1, "H5": 1, "H6": 1, "H7": 0, "H8": 0,
    "H9": 1, "H10": 0, "H11": 1, "H12": 2, "H13": 1, "H14": 0, "H15": 0,
    "H16": 0, "H17": 0, "H18": 1, "H19": 0, "H20": 1,
    # I 组合管理
    "I1": 2, "I2": 2, "I3": 2, "I4": 2, "I5": 2, "I6": 2, "I7": 2, "I8": 2,
    "I9": 2, "I10": 1, "I11": 0, "I12": 0, "I13": 0, "I14": 0, "I15": 0,
    "I16": 0, "I17": 0, "I18": 0, "I19": 0, "I20": 0,
    # J 工程质量
    "J1": 1, "J2": 2, "J3": 2, "J4": 2, "J5": 2, "J6": 2, "J7": 2, "J8": 2,
    "J9": 2, "J10": 2, "J11": 2, "J12": 2, "J13": 1, "J14": 2, "J15": 0,
    "J16": 1, "J17": 1, "J18": 0, "J19": 1, "J20": 0,
}
